### ISSUE TITLE
Cosmic Coding Muts v76

### ISSUE THREAD

**Issue by dgaston** [quinlan-lab/vcftidy#1]
I'm trying to run tidy on the newest Cosmic release and run into the following error:

`python ~/Software/vcftidy/vcftidy.py CosmicCodingMuts.vcf ./GATK-Bundle/2.8/b37/human_g1k_v37.fasta > CosmicCodingMuts.tidy.vcf`

```
TestResults(failed=0, attempted=49)
Traceback (most recent call last):
  File "/home/dgaston/Software/vcftidy/vcftidy.py", line 535, in <module>
    sys.exit(main(fh, ref))
  File "/home/dgaston/Software/vcftidy/vcftidy.py", line 503, in main
    for v in gen_variants(fh):
  File "/home/dgaston/Software/vcftidy/vcftidy.py", line 480, in gen_variants
    fields[1], fields[3], fields[4] = leftnorm(fields[0], pos, ref, alts[0], fa)
  File "/home/dgaston/Software/vcftidy/vcftidy.py", line 448, in leftnorm
    return normalize(*leftalign(chrom, pos, ref, alt, fa), left_only=True)
  File "/home/dgaston/Software/vcftidy/vcftidy.py", line 330, in leftalign
    assert seq.endswith(ref), (chrom, pos, ref, alt, seq[-10:])
AssertionError: ('1', 451181, 'T', 'A', u'TGTATATGTA')
```

I have successfully ran the software on the newest release of ClinVar

**Comment by brentp** [comment]
Are you sure that your vcf is from version 37 and not version 38?

**Comment by dgaston** [comment]
Whoops. Stupid me. Yup, that's the issue.

**Comment by brentp** [comment]
no problem. any reason you're using vcftidy instead of vt?

**Comment by dgaston** [comment]
Still seems to run into an error, but now not until the Y chromosome:

```
TestResults(failed=0, attempted=49)
Traceback (most recent call last):
  File "/home/dgaston/Software/vcftidy/vcftidy.py", line 535, in <module>
    sys.exit(main(fh, ref))
  File "/home/dgaston/Software/vcftidy/vcftidy.py", line 503, in main
    for v in gen_variants(fh):
  File "/home/dgaston/Software/vcftidy/vcftidy.py", line 480, in gen_variants
    fields[1], fields[3], fields[4] = leftnorm(fields[0], pos, ref, alts[0], fa)
  File "/home/dgaston/Software/vcftidy/vcftidy.py", line 448, in leftnorm
    return normalize(*leftalign(chrom, pos, ref, alt, fa), left_only=True)
  File "/home/dgaston/Software/vcftidy/vcftidy.py", line 330, in leftalign
    assert seq.endswith(ref), (chrom, pos, ref, alt, seq[-10:])
AssertionError: ('Y', 252051, 'GT', 'G', u'NNNNNNNNNN')
```

**Comment by dgaston** [comment]
Just for testing purposes really to see how it compares in terms of speed and workflow. I'm updating my local Cosmic and ClinVar resources for vcfanno as opposed to the ones currently distributed with GEMINI.

**Comment by brentp** [comment]
cool. if you're getting resources for vcfanno, you can refer to this config: https://github.com/brentp/vcfanno/blob/master/example/gem.conf

and let me know if you come up with additional resources. As you gather, we'll be doing this soon.

**Comment by dgaston** [comment]
Yes, I am using that config. I've added in some additional fields to pull from ClinVar and Cosmic for my annotations and added post annotations for max_aaf_all and max_aaf_no_fin (to replicate the max_aaf in GEMINI). Right now I have ClinVar and COSMIC updated as there were some mistakes in the old ClinVar for variants I am filtering and flagging for clinical reports.
