### ISSUE TITLE
AC-field decomposition!

### ISSUE THREAD

**Issue by alphahmed18** [quinlan-lab/vcftidy#2]
I had multiple error messages after running tidyvcf, complaining about "Incorrect number of FORMAT fields."
After closely examining the output, I realized that during the decomposition process, the AC parameter still lists the total number of alleles separated by a comma.
I wonder if I'm doing something wrong? When I ran the vt tool, I didn't have the same result.

Best regards,
Ahmed

**Comment by brentp** [comment]
I should update the readme, but this project is abandoned. Use vt normalize/decompose instead.

**Comment by alphahmed18** [comment]
Thanks a lot!
